# Generated by Django 6.1.1 on 2026-09-02 20:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_customer_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='merchants.merchant')),
            ],
            options={
                'indexes': [models.Index(fields=['merchant', 'email'], name='customers_c_merchan_dfaa06_idx'), models.Index(fields=['razorpay_customer_id'], name='customers_c_razorpa_9b741b_idx')],
                'constraints': [models.UniqueConstraint(fields=('merchant', 'razorpay_customer_id'), name='unique_customer_per_merchant')],
            },
        ),
    ]
