# Generated by Django 6.1.1 on 2026-09-02 20:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_payment_id', models.CharField(max_length=100)),
                ('amount_paise', models.IntegerField()),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customers.customer')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='merchants.merchant')),
            ],
            options={
                'indexes': [models.Index(fields=['merchant', 'status'], name='payments_pa_merchan_42884d_idx'), models.Index(fields=['razorpay_payment_id'], name='payments_pa_razorpa_4059b1_idx'), models.Index(fields=['customer', 'status'], name='payments_pa_custome_25a299_idx')],
                'constraints': [models.UniqueConstraint(fields=('merchant', 'razorpay_payment_id'), name='unique_payment_per_merchant')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_subscription_id', models.CharField(max_length=100)),
                ('plan_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('plan_amount_paise', models.IntegerField()),
                ('cycle_number', models.IntegerField(default=1)),
                ('current_start', models.DateTimeField(blank=True, null=True)),
                ('current_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='customers.customer')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='merchants.merchant')),
            ],
            options={
                'indexes': [models.Index(fields=['merchant', 'status'], name='payments_su_merchan_87d7e2_idx'), models.Index(fields=['razorpay_subscription_id'], name='payments_su_razorpa_9f5b57_idx'), models.Index(fields=['customer', 'status'], name='payments_su_custome_9c4393_idx')],
                'constraints': [models.UniqueConstraint(fields=('merchant', 'razorpay_subscription_id'), name='unique_subscription_per_merchant')],
            },
        ),
    ]
