# Generated by Django 6.1.1 on 2026-09-03 12:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DIAGNOSING', 'Diagnosing'), ('ACTION_PENDING', 'Action Pending'), ('RECOVERED', 'Recovered'), ('FAILED', 'Failed'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('retries_attempted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_diagnosis', models.TextField(blank=True, null=True)),
                ('latest_recommendation', models.CharField(blank=True, max_length=50, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_case', to='payments.payment')),
            ],
        ),
    ]
