# Generated by Django 6.1.1 on 2026-09-21 11:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('recovery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDiagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('failure_category', models.CharField(choices=[('INSUFFICIENT_FUNDS', 'Insufficient funds'), ('CARD_EXPIRED', 'Card expired'), ('BANK_DECLINED', 'Bank declined'), ('NETWORK_ERROR', 'Network error'), ('PAYMENT_METHOD_INVALID', 'Payment method invalid'), ('CUSTOMER_INITIATED_FAILURE', 'Customer initiated failure'), ('UNKNOWN', 'Unknown')], max_length=40)),
                ('diagnosis', models.TextField()),
                ('confidence', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('reasoning_summary', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recovery_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_diagnoses', to='recovery.recoverycase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommended_action', models.CharField(choices=[('RETRY_PAYMENT', 'Retry payment'), ('SEND_PAYMENT_LINK', 'Send payment link'), ('SEND_REMINDER', 'Send reminder'), ('SCHEDULE_RETRY', 'Schedule retry'), ('ESCALATE_TO_HUMAN', 'Escalate to human'), ('STOP_RECOVERY', 'Stop recovery')], max_length=30)),
                ('suggested_timing', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('AFTER_24H', 'After 24 hours'), ('AFTER_48H', 'After 48 hours'), ('NOT_APPLICABLE', 'Not applicable')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recovery.aidiagnosis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuardrailIntervention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_action', models.CharField(choices=[('RETRY_PAYMENT', 'Retry payment'), ('SEND_PAYMENT_LINK', 'Send payment link'), ('SEND_REMINDER', 'Send reminder'), ('SCHEDULE_RETRY', 'Schedule retry'), ('ESCALATE_TO_HUMAN', 'Escalate to human'), ('STOP_RECOVERY', 'Stop recovery')], max_length=30)),
                ('resulting_action', models.CharField(choices=[('RETRY_PAYMENT', 'Retry payment'), ('SEND_PAYMENT_LINK', 'Send payment link'), ('SEND_REMINDER', 'Send reminder'), ('SCHEDULE_RETRY', 'Schedule retry'), ('ESCALATE_TO_HUMAN', 'Escalate to human'), ('STOP_RECOVERY', 'Stop recovery')], max_length=30)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated')], max_length=10)),
                ('reason_code', models.CharField(max_length=60)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardrail_interventions', to='recovery.airecommendation')),
                ('recovery_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardrail_interventions', to='recovery.recoverycase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('RETRY_PAYMENT', 'Retry payment'), ('SEND_PAYMENT_LINK', 'Send payment link'), ('SEND_REMINDER', 'Send reminder'), ('SCHEDULE_RETRY', 'Schedule retry'), ('ESCALATE_TO_HUMAN', 'Escalate to human'), ('STOP_RECOVERY', 'Stop recovery')], max_length=30)),
                ('authorization_status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated')], max_length=10)),
                ('execution_status', models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_actions', to='recovery.airecommendation')),
                ('recovery_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_actions', to='recovery.recoverycase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_retries_per_case', models.PositiveSmallIntegerField(default=3)),
                ('recovery_window_days', models.PositiveSmallIntegerField(default=7)),
                ('duplicate_action_cooldown_hours', models.PositiveSmallIntegerField(default=24)),
                ('high_value_threshold_paise', models.PositiveIntegerField(default=50000)),
                ('escalation_failure_threshold', models.PositiveSmallIntegerField(default=2)),
                ('no_retry_on_fraud', models.BooleanField(default=True)),
                ('abandonment_timeout_days', models.PositiveSmallIntegerField(default=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_policy', to='merchants.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('RECOVERED', 'Recovered'), ('FAILED', 'Failed'), ('ESCALATED', 'Escalated'), ('STOPPED', 'Stopped'), ('PENDING_RESULT', 'Pending result')], max_length=20)),
                ('recovered_amount_paise', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recovery_action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='recovery.recoveryaction')),
                ('recovery_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_results', to='recovery.recoverycase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
